# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-06-06 21:20
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Planned_Site_Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planned_start_date', models.DateField(null=True)),
                ('planned_end_date', models.DateField(null=True)),
                ('funder', models.TextField(null=True)),
                ('status', models.CharField(choices=[('C', 'Completed'), ('P', 'In Progress'), ('W', 'Wishlist'), ('F', 'Forthcoming')], max_length=1)),
                ('name', models.TextField(null=True)),
                ('eez_boundary', django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=4326)),
                ('site_id', models.IntegerField(null=True)),
                ('team_id', models.IntegerField(null=True)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='plannedsite',
            name='status',
            field=models.CharField(choices=[('C', 'Completed'), ('P', 'In Progress'), ('W', 'Wishlist'), ('F', 'Forthcoming')], max_length=1),
        ),
    ]
