# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-06-07 17:25
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_auto_20170606_2120'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventAttributeSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_code', models.CharField(max_length=32)),
                ('event_time', models.IntegerField(default=0, help_text='ms')),
                ('zero_time_em_note', models.BooleanField()),
                ('haul_time_em_note', models.BooleanField()),
                ('zero_time_tagged', models.BooleanField()),
                ('sixty_minute_time_tagged', models.BooleanField()),
                ('ninty_minute_time_tagged', models.BooleanField()),
                ('haul_time_tagged', models.BooleanField()),
                ('max_n_tagged', models.BooleanField()),
                ('numeric_value_from_event_note', models.IntegerField()),
                ('numeric_value_from_obs_comment', models.IntegerField()),
            ],
            options={
                'db_table': 'event_attribute_summary',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HabitatSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('site', models.CharField(max_length=100)),
                ('reef', models.CharField(max_length=100)),
                ('reef_habitat_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'habitat_summary',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PlannedSiteStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planned_start_date', models.DateField(null=True)),
                ('planned_end_date', models.DateField(null=True)),
                ('funder', models.TextField(null=True)),
                ('status', models.CharField(choices=[('F', 'Forthcoming'), ('P', 'In Progress'), ('W', 'Wishlist'), ('C', 'Completed')], max_length=1)),
                ('name', models.TextField(null=True)),
                ('eez_boundary', django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=4326)),
                ('site_id', models.IntegerField(null=True)),
                ('team_id', models.IntegerField(null=True)),
            ],
            options={
                'managed': False,
            },
        ),
    ]
