# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-06-16 09:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_auto_20170607_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plannedsite',
            name='status',
            field=models.CharField(choices=[('C', 'Completed'), ('W', 'Wishlist'), ('P', 'In Progress'), ('F', 'Forthcoming')], max_length=1),
        ),
    ]
