# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-06-16 09:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0004_auto_20170616_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plannedsite',
            name='status',
            field=models.CharField(choices=[('P', 'In Progress'), ('F', 'Forthcoming'), ('W', 'Wishlist'), ('C', 'Completed')], max_length=1),
        ),
    ]
