# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-13 19:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0006_auto_20170616_1248'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyLeaderboard',
            fields=[
                ('leaderboard_id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('affiliation_name', models.TextField()),
                ('month', models.TextField()),
                ('num_assignments', models.IntegerField()),
                ('hours', models.DecimalField(decimal_places=2, max_digits=12)),
                ('affiliation_count_rank', models.IntegerField()),
                ('affiliation_hour_rank', models.IntegerField()),
            ],
            options={
                'db_table': 'monthly_leaderboard',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ObservationSummary',
            fields=[
                ('summary_id', models.IntegerField(primary_key=True, serialize=False)),
                ('trip_code', models.TextField()),
                ('set_code', models.TextField()),
                ('full_code', models.TextField()),
                ('region_name', models.TextField()),
                ('location_name', models.TextField()),
                ('site_name', models.TextField()),
                ('reef_name', models.TextField()),
                ('reef_habitat_name', models.TextField()),
                ('animal_id', models.IntegerField()),
                ('family', models.TextField()),
                ('genus', models.TextField()),
                ('species', models.TextField()),
                ('maxn', models.IntegerField()),
                ('event_time_minutes_raw', models.TextField()),
                ('event_time_minutes', models.TextField()),
                ('trip_id', models.IntegerField()),
                ('set_id', models.IntegerField()),
                ('video_id', models.IntegerField()),
            ],
            options={
                'db_table': 'observation_summary',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SetSummary',
            fields=[
                ('set_id', models.IntegerField(primary_key=True, serialize=False)),
                ('team', models.TextField()),
                ('trip_code', models.TextField()),
                ('set_code', models.TextField()),
                ('region_name', models.TextField()),
                ('location_name', models.TextField()),
                ('site_name', models.TextField()),
                ('reef_name', models.TextField()),
                ('reef_habitat_name', models.TextField()),
                ('reef_habitat_id', models.IntegerField()),
                ('set_date', models.DateField()),
                ('drop_time', models.TimeField()),
                ('haul_time', models.TimeField()),
                ('wkt_coordinates', models.TextField()),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=10)),
                ('depth', models.DecimalField(decimal_places=2, max_digits=6)),
                ('equipment_frame_type', models.TextField()),
                ('equipment_camera', models.TextField()),
                ('equipment_stereo_camera', models.BooleanField()),
                ('equipment_camera_height', models.TextField()),
                ('equipment_arm_length', models.TextField()),
                ('bait_preparation', models.TextField()),
                ('bait_type', models.TextField()),
                ('bait_oiled', models.BooleanField()),
                ('visibility', models.TextField()),
                ('current_flow_estimated', models.TextField()),
                ('current_flow_instrumented', models.DecimalField(decimal_places=2, max_digits=6)),
                ('substrate_type', models.TextField()),
                ('substrate_complexity_type', models.TextField()),
                ('bruv_image_url', models.TextField()),
                ('splendor_image_url', models.TextField()),
                ('video_file_name', models.TextField()),
                ('video_source', models.TextField()),
                ('video_path', models.TextField()),
            ],
            options={
                'db_table': 'set_summary',
                'managed': False,
            },
        ),
    ]
