# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-15 20:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0007_auto_20170813_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plannedsite',
            name='status',
            field=models.CharField(choices=[('C', 'Completed'), ('P', 'In Progress'), ('W', 'Wishlist'), ('F', 'Forthcoming')], max_length=1),
        ),
    ]
