# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-09-20 17:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0009_test1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_name', models.CharField(max_length=50)),
                ('report_status', models.CharField(max_length=500, null=True)),
                ('include', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='plannedsite',
            name='status',
            field=models.CharField(choices=[('C', 'Completed'), ('P', 'In Progress'), ('W', 'Wishlist'), ('F', 'Forthcoming')], max_length=1),
        ),
    ]
