# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-09-20 19:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0010_new_features'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plannedsite',
            name='status',
            field=models.CharField(choices=[('F', 'Forthcoming'), ('P', 'In Progress'), ('C', 'Completed'), ('W', 'Wishlist')], max_length=1),
        ),
    ]
