# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-01 03:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotator',
            name='token',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='token',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='observation',
            name='stage',
            field=models.CharField(choices=[('JU', 'Juvenile'), ('AD', 'Adult'), ('U', 'Unknown')], default='U', max_length=2),
        ),
        migrations.AlterField(
            model_name='videoannotator',
            name='status',
            field=models.CharField(choices=[('I', 'In progress'), ('N', 'Not started'), ('D', 'Disabled'), ('C', 'Competed')], default='N', max_length=1),
        ),
    ]
