# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-15 21:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0003_auto_20160215_1910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='observation',
            name='behavior',
        ),
        migrations.AddField(
            model_name='observation',
            name='behaviors',
            field=models.ManyToManyField(to='annotation.AnimalBehavior'),
        )
    ]
