# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-12 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0003_auto_20160106_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='observation',
            name='comment',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='observation',
            name='sex',
            field=models.CharField(choices=[('M', 'Male'), ('U', 'Unknown'), ('F', 'Female')], default='U', max_length=1),
        ),
        migrations.AlterField(
            model_name='observation',
            name='stage',
            field=models.CharField(choices=[('U', 'Unknown'), ('AD', 'Adult'), ('JU', 'Juvenile')], default='U', max_length=2),
        ),
        migrations.AlterField(
            model_name='videoannotator',
            name='status',
            field=models.CharField(choices=[('I', 'In progress'), ('C', 'Competed'), ('N', 'Not started')], default='N', max_length=1),
        ),
    ]
