# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-02 00:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0004_auto_20160215_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='duration',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
