# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-02 00:46
from __future__ import unicode_literals

import config.current_user
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('annotation', '0005_auto_20160302_0028'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalObservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_datetime', models.DateTimeField(auto_now_add=True)),
                ('last_modified_datetime', models.DateTimeField(auto_now=True)),
                ('sex', models.CharField(choices=[('U', 'Unknown'), ('M', 'Male'), ('F', 'Female')], default='U', max_length=1)),
                ('stage', models.CharField(choices=[('AD', 'Adult'), ('U', 'Unknown'), ('JU', 'Juvenile')], default='U', max_length=2)),
                ('length', models.IntegerField(help_text='centimeters', null=True)),
                ('gear_on_animal', models.BooleanField(default=False)),
                ('gear_fouled', models.BooleanField(default=False)),
                ('tag', models.CharField(choices=[('O', 'Other'), ('D', 'Dart tag'), ('R', 'Roto tag'), ('N', 'None')], default='N', max_length=1)),
                ('external_parasites', models.BooleanField(default=False)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annotation.Animal')),
                ('behaviors', models.ManyToManyField(to='annotation.AnimalBehavior')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='observation',
            name='animal',
        ),
        migrations.RemoveField(
            model_name='observation',
            name='behaviors',
        ),
        migrations.RemoveField(
            model_name='observation',
            name='external_parasites',
        ),
        migrations.RemoveField(
            model_name='observation',
            name='gear_fouled',
        ),
        migrations.RemoveField(
            model_name='observation',
            name='gear_on_animal',
        ),
        migrations.RemoveField(
            model_name='observation',
            name='length',
        ),
        migrations.RemoveField(
            model_name='observation',
            name='sex',
        ),
        migrations.RemoveField(
            model_name='observation',
            name='stage',
        ),
        migrations.RemoveField(
            model_name='observation',
            name='tag',
        ),
        migrations.AddField(
            model_name='observation',
            name='type',
            field=models.CharField(choices=[('I', 'Of interest'), ('A', 'Animal')], default='I', max_length=1),
        ),
        migrations.AddField(
            model_name='animalobservation',
            name='observation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='annotation.Observation'),
        ),
        migrations.AddField(
            model_name='animalobservation',
            name='user',
            field=models.ForeignKey(default=config.current_user.get_current_user, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
