# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-03 21:40
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0006_auto_20160302_0046'),
    ]

    operations = [
        migrations.AddField(
            model_name='observation',
            name='extent',
            field=django.contrib.gis.db.models.fields.PolygonField(null=True, srid=4326),
        )
    ]
