# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-15 17:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0009_auto_20160315_1425'),
    ]

    operations = [
        migrations.RemoveField(
                model_name='observation',
                name='initial_observation_time',
        ),
        migrations.AddField(
            model_name='observation',
            name='initial_observation_time',
            field=models.IntegerField(help_text='ms'),
        ),
    ]
