# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-29 22:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0011_auto_20160329_2053'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='annotationstate',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='videoannotator',
            name='progress',
            field=models.IntegerField(default=0),
        ),
    ]
