# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-08 18:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0004_auto_20160408_1804'),
        ('annotation', '0012_auto_20160329_2211'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VideoAnnotator',
            new_name='Assignment',
        ),
        migrations.RemoveField(
            model_name='annotator',
            name='affiliation',
        ),
        migrations.RemoveField(
            model_name='annotator',
            name='user',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='affiliation',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='user',
        ),
        migrations.RenameField(
            model_name='observation',
            old_name='video_annotator',
            new_name='assignment',
        ),
        migrations.AlterField(
            model_name='assignment',
            name='annotator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.FinprintUser'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='assigned_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_by', to='core.FinprintUser'),
        ),
        migrations.DeleteModel(
            name='Annotator',
        ),
        migrations.DeleteModel(
            name='Lead',
        ),
    ]
