# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-12 23:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0014_auto_20160412_2312'),
    ]

    operations = [
        migrations.RunSQL('''
        UPDATE annotation_observation ao SET created_by_id = (SELECT id FROM core_finprintuser WHERE user_id = ao.user_id);
        UPDATE annotation_observation ao SET updated_by_id = (SELECT id FROM core_finprintuser WHERE user_id = ao.user_id);
        '''),
    ]
