# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-10 16:14
from __future__ import unicode_literals

import config.current_user
from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('annotation', '0016_auto_20160418_1652'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='annotation.Attribute')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('_default_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_datetime', models.DateTimeField(auto_now_add=True)),
                ('last_modified_datetime', models.DateTimeField(auto_now=True)),
                ('extent', django.contrib.gis.db.models.fields.PolygonField(null=True, srid=4326)),
                ('attribute', models.ManyToManyField(to='annotation.Attribute')),
                ('user', models.ForeignKey(default=config.current_user.get_current_user, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='observationimage',
            name='observation',
        ),
        migrations.RemoveField(
            model_name='observationimage',
            name='user',
        ),
        migrations.RemoveField(
            model_name='observationimage',
            name='video',
        ),
        migrations.RemoveField(
            model_name='siteimage',
            name='user',
        ),
        migrations.RemoveField(
            model_name='siteimage',
            name='video',
        ),
        migrations.RemoveField(
            model_name='animalobservation',
            name='behaviors',
        ),
        migrations.RemoveField(
            model_name='animalobservation',
            name='features',
        ),
        migrations.RemoveField(
            model_name='observation',
            name='extent',
        ),
        migrations.AlterField(
            model_name='animalobservation',
            name='sex',
            field=models.CharField(choices=[('U', 'Unknown'), ('M', 'Male'), ('F', 'Female')], default='U', max_length=1),
        ),
        migrations.AlterField(
            model_name='animalobservation',
            name='stage',
            field=models.CharField(choices=[('JU', 'Juvenile'), ('U', 'Unknown'), ('AD', 'Adult')], default='U', max_length=2),
        ),
        migrations.AlterField(
            model_name='observation',
            name='type',
            field=models.CharField(choices=[('I', 'Of interest'), ('A', 'Animal')], default='I', max_length=1),
        ),
        migrations.DeleteModel(
            name='AnimalBehavior',
        ),
        migrations.DeleteModel(
            name='ObservationFeature',
        ),
        migrations.DeleteModel(
            name='ObservationImage',
        ),
        migrations.DeleteModel(
            name='SiteImage',
        ),
    ]
