# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-14 17:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0019_drop_obs_columns'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='lead_only',
            field=models.BooleanField(default=False),
        ),
    ]
