# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-08 15:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0021_auto_20160804_0031'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attribute',
            options={'verbose_name': 'Tag'},
        ),
        migrations.AddField(
            model_name='animal',
            name='caab_code',
            field=models.PositiveIntegerField(blank=True, help_text='Enter CAAB code without spaces', null=True, verbose_name='CAAB code'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='fishbase_key',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='FishBase key'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='sealifebase_key',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='SeaLifeBase key'),
        ),
        migrations.AlterField(
            model_name='animalobservation',
            name='sex',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('U', 'Unknown')], default='U', max_length=1),
        ),
        migrations.AlterField(
            model_name='animalobservation',
            name='stage',
            field=models.CharField(choices=[('JU', 'Juvenile'), ('AD', 'Adult'), ('U', 'Unknown')], default='U', max_length=2),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='active',
            field=models.BooleanField(default=True, help_text='overridden if parent is inactive'),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='lead_only',
            field=models.BooleanField(default=False, help_text='overridden if parent is lead only'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='type',
            field=models.CharField(choices=[('A', 'Animal'), ('I', 'Of interest')], default='I', max_length=1),
        ),
    ]
