# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-10 22:44
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0022_auto_20160808_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='raw_import_json',
            field=models.TextField(null=True),
        ),
    ]
