# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-20 15:44
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0024_auto_20160812_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='caab_code',
            field=models.PositiveIntegerField(blank=True, help_text='Enter CAAB code without spaces', null=True, validators=[django.core.validators.MaxValueValidator(99999999)], verbose_name='CAAB code'),
        ),
        migrations.AlterField(
            model_name='animalobservation',
            name='sex',
            field=models.CharField(choices=[('U', 'Unknown'), ('F', 'Female'), ('M', 'Male')], default='U', max_length=1),
        ),
        migrations.AlterField(
            model_name='animalobservation',
            name='stage',
            field=models.CharField(choices=[('U', 'Unknown'), ('AD', 'Adult'), ('JU', 'Juvenile')], default='U', max_length=2),
        ),
        migrations.AlterUniqueTogether(
            name='animal',
            unique_together=set([('family', 'genus', 'species')]),
        ),
    ]
