# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-11-11 19:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0030_project_animal_data_migration'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='annotation.Project'),
        ),
        migrations.AddField(
            model_name='attribute',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='annotation.Project'),
        ),
    ]
