# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-12-13 23:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0033_auto_20161114_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterrecord',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='annotation.Project'),
        ),
        migrations.AlterField(
            model_name='masterrecord',
            name='set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bruv.Set'),
        ),
        migrations.AlterUniqueTogether(
            name='masterrecord',
            unique_together=set([('set', 'project')]),
        ),
    ]
