# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-12-14 18:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0034_auto_20161213_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='attribute',
            unique_together=set([('name', 'project')]),
        ),
    ]
