# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-11-11 19:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


def create_default_project(apps, schema_editor):
    Video = apps.get_model('annotation', 'Video')
    VideoFile = apps.get_model('annotation', 'VideoFile')
    db_alias = schema_editor.connection.alias
    VideoFile.objects.using(db_alias).bulk_create(
        list(VideoFile(file=v.file, rank=1, primary=True, video=v, user_id=1)
             for v in Video.objects.all() if v.file != '')
    )


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('annotation', '0036_auto_20161221_2249'),
    ]

    operations = [
        migrations.RunPython(create_default_project),
    ]
