# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-12-21 23:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0037_video_file_data_migration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='file',
        ),
        migrations.RemoveField(
            model_name='video',
            name='source_folder',
        ),
    ]
