# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-12-23 18:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0038_auto_20161221_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videofile',
            name='primary',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='videofile',
            name='rank',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
