# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-01-16 18:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0040_auto_20161223_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='needs_review',
            field=models.BooleanField(default=False),
        ),
    ]
