# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-01-17 00:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0042_auto_20170116_2103'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterEventMeasurable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
                ('master_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annotation.MasterEvent')),
            ],
        ),
        migrations.CreateModel(
            name='Measurable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='mastereventmeasurable',
            name='measurable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annotation.Measurable'),
        ),
        migrations.AddField(
            model_name='masterevent',
            name='measurables',
            field=models.ManyToManyField(through='annotation.MasterEventMeasurable', to='annotation.Measurable'),
        ),
    ]
