# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-05-18 15:57
from __future__ import unicode_literals

from django.db import migrations, models


def create_master_record_states(apps, schema_editor):
    MasterRecordState = apps.get_model('annotation', 'MasterRecordState')
    db_alias = schema_editor.connection.alias
    try:
        MasterRecordState.objects.using(db_alias).bulk_create([
            MasterRecordState(id=1, name='In progress', description=''),
            MasterRecordState(id=2, name='Completed', description=''),
            MasterRecordState(id=3, name='Deprecated', description=''),
        ])
    except:
        pass


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0045_auto_20170117_0023'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterRecordState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField()),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.RunPython(create_master_record_states),
    ]
