# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-05-18 16:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0046_auto_20170518_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterrecord',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE,
                                    to='annotation.MasterRecordState'),
            preserve_default=False,
        ),
    ]
