# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-05-18 16:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0047_auto_20170518_1629'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='masterrecord',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='masterrecord',
            name='deprecated',
        ),
    ]
