# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-05-25 14:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0048_auto_20170518_1629'),
    ]

    operations = [
        migrations.RunSQL('''
            update annotation_annotationstate
            set name = 'Reviewed'
            where id = 4; 
        ''')
    ]
