# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-06-07 14:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('annotation', '0051_auto_20170607_1420'),
    ]

    operations = [
        migrations.RunSQL('''
            -- add all animals to the Global Finprint project
            INSERT INTO annotation_animal_projects
            (
              animal_id,
              project_id
            )
              SELECT
                a.id,
                p.id
              FROM
                annotation_animal a,
                annotation_project p
              WHERE a.id NOT IN
                    (
                      SELECT animal_id
                      FROM annotation_animal_projects
                    )
                    AND p.name = 'Global FinPrint Project';
                    '''),
        migrations.RunSQL('''
          INSERT INTO annotation_globalattribute
            (id, name, description, lft, rght, tree_id, level, parent_id)
              SELECT
                a.id,
                a.name,
                a.description,
                a.lft,
                a.rght,
                a.tree_id,
                a.level,
                a.parent_id
                  annotation_globalattribute
              FROM annotation_attribute a
                LEFT JOIN annotation_globalattribute g ON g.id = a.id
              WHERE a.name IN
                    (
                      'Image Frame tags'
                    )
                    AND g.id IS NULL;
            
            INSERT INTO annotation_globalattribute
            (id, name, description, lft, rght, tree_id, level, parent_id)
              SELECT
                a.id,
                a.name,
                a.description,
                a.lft,
                a.rght,
                a.tree_id,
                a.level,
                a.parent_id
                  annotation_globalattribute
              FROM annotation_attribute a
                LEFT JOIN annotation_globalattribute g ON g.id = a.id
              WHERE a.name IN
                    (
                      'MaxN image frame',
                      'MARK ZERO TIME',
                      'MARK HAUL TIME',
                      'MARK 90 MIN TIME',
                      'MARK 60 MIN TIME'
                    )
                    AND g.id IS NULL;
            
            UPDATE annotation_attribute
            SET global_parent_id = id
            WHERE id IN
                  (
                    SELECT id
                    FROM annotation_globalattribute
                  );
        ''')
    ]
