# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-06-16 09:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0052_auto_20170607_1457'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='attribute',
            managers=[
                ('objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='globalattribute',
            managers=[
                ('objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='animalobservation',
            name='sex',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('U', 'Unknown')], default='U', max_length=1),
        ),
        migrations.AlterField(
            model_name='animalobservation',
            name='stage',
            field=models.CharField(choices=[('AD', 'Adult'), ('JU', 'Juvenile'), ('U', 'Unknown')], default='U', max_length=2),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='global_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='annotation.GlobalAttribute'),
        ),
        migrations.AlterField(
            model_name='masteranimalobservation',
            name='sex',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('U', 'Unknown')], default='U', max_length=1),
        ),
        migrations.AlterField(
            model_name='masterobservation',
            name='type',
            field=models.CharField(choices=[('A', 'Animal'), ('I', 'Of interest')], default='I', max_length=1),
        ),
    ]
