# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-06-16 09:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0053_auto_20170616_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animalobservation',
            name='sex',
            field=models.CharField(choices=[('U', 'Unknown'), ('F', 'Female'), ('M', 'Male')], default='U', max_length=1),
        ),
        migrations.AlterField(
            model_name='animalobservation',
            name='stage',
            field=models.CharField(choices=[('AD', 'Adult'), ('U', 'Unknown'), ('JU', 'Juvenile')], default='U', max_length=2),
        ),
        migrations.AlterField(
            model_name='masteranimalobservation',
            name='sex',
            field=models.CharField(choices=[('U', 'Unknown'), ('F', 'Female'), ('M', 'Male')], default='U', max_length=1),
        ),
        migrations.AlterField(
            model_name='masteranimalobservation',
            name='stage',
            field=models.CharField(choices=[('AD', 'Adult'), ('U', 'Unknown'), ('JU', 'Juvenile')], default='U', max_length=2),
        ),
        migrations.AlterField(
            model_name='masterobservation',
            name='type',
            field=models.CharField(choices=[('I', 'Of interest'), ('A', 'Animal')], default='I', max_length=1),
        ),
        migrations.AlterField(
            model_name='observation',
            name='type',
            field=models.CharField(choices=[('I', 'Of interest'), ('A', 'Animal')], default='I', max_length=1),
        ),
    ]
