# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-24 20:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0055_auto_20170616_1248'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventMeasurable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annotation.Event')),
                ('measurable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annotation.Measurable')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='measurables',
            field=models.ManyToManyField(through='annotation.EventMeasurable', to='annotation.Measurable'),
        ),
    ]
