# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-09 21:18
from __future__ import unicode_literals

import config.current_user
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('annotation', '0057_auto_20170811_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='animalobservation',
            name='last_modified_by',
            field=models.ForeignKey(default=config.current_user.get_current_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='annotation_animalobservation_last_modified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assignment',
            name='last_modified_by',
            field=models.ForeignKey(default=config.current_user.get_current_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='annotation_assignment_last_modified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='last_modified_by',
            field=models.ForeignKey(default=config.current_user.get_current_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='annotation_event_last_modified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='masteranimalobservation',
            name='last_modified_by',
            field=models.ForeignKey(default=config.current_user.get_current_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='annotation_masteranimalobservation_last_modified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='masterevent',
            name='last_modified_by',
            field=models.ForeignKey(default=config.current_user.get_current_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='annotation_masterevent_last_modified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='masterobservation',
            name='last_modified_by',
            field=models.ForeignKey(default=config.current_user.get_current_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='annotation_masterobservation_last_modified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='masterrecord',
            name='last_modified_by',
            field=models.ForeignKey(default=config.current_user.get_current_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='annotation_masterrecord_last_modified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='observation',
            name='last_modified_by',
            field=models.ForeignKey(default=config.current_user.get_current_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='annotation_observation_last_modified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='last_modified_by',
            field=models.ForeignKey(default=config.current_user.get_current_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='annotation_project_last_modified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='video',
            name='last_modified_by',
            field=models.ForeignKey(default=config.current_user.get_current_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='annotation_video_last_modified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='videofile',
            name='last_modified_by',
            field=models.ForeignKey(default=config.current_user.get_current_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='annotation_videofile_last_modified_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
