# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-29 01:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0059_auto_20171113_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterobservation',
            name='generation_duration',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='observation',
            name='generation_duration',
            field=models.FloatField(null=True),
        ),
    ]
