# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-09-20 17:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0062_test1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animalobservation',
            name='sex',
            field=models.CharField(choices=[('U', 'Unknown'), ('F', 'Female'), ('M', 'Male')], default='U', max_length=1),
        ),
        migrations.AlterField(
            model_name='masteranimalobservation',
            name='sex',
            field=models.CharField(choices=[('U', 'Unknown'), ('F', 'Female'), ('M', 'Male')], default='U', max_length=1),
        ),
    ]
