# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-20 22:28
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FishingRestrictions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=16)),
                ('description', models.CharField(max_length=48)),
            ],
            options={
                'verbose_name_plural': 'Fishing restrictions',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(help_text='3166-1 alpha-2, if applicable.', max_length=2, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MPA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('boundary', django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=4326)),
                ('area', models.PositiveIntegerField(help_text='km^2')),
                ('founded', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name_plural': 'MPAs',
                'verbose_name': 'MPA',
            },
        ),
        migrations.CreateModel(
            name='MPACompliance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=16)),
                ('description', models.CharField(max_length=48)),
            ],
            options={
                'verbose_name_plural': 'MPA compliance',
                'verbose_name': 'MPA compliance',
            },
        ),
        migrations.CreateModel(
            name='MPAIsolation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=24)),
            ],
            options={
                'verbose_name_plural': 'MPA isolation',
                'verbose_name': 'MPA isolation',
            },
        ),
        migrations.CreateModel(
            name='ProtectionStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=16)),
                ('description', models.CharField(max_length=48)),
            ],
            options={
                'verbose_name_plural': 'Protection status',
            },
        ),
        migrations.CreateModel(
            name='Reef',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Must be unique for reef site.', max_length=100)),
                ('code', models.CharField(help_text='Must be unique for reef site.', max_length=1)),
                ('boundary', django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=4326)),
                ('fishing_restrictions', models.ManyToManyField(blank=True, to='habitat.FishingRestrictions')),
                ('mpa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='habitat.MPA')),
                ('protection_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='habitat.ProtectionStatus')),
            ],
        ),
        migrations.CreateModel(
            name='ReefHabitat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ReefType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=16)),
                ('code', models.CharField(max_length=1)),
                ('description', models.CharField(max_length=48)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SharkGearInUse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=24)),
                ('description', models.CharField(max_length=48)),
            ],
            options={
                'verbose_name_plural': 'Shark gear in use',
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Must be unique for site location.', max_length=100)),
                ('code', models.CharField(help_text='Must be unique for site location.', max_length=2)),
                ('boundary', django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=4326)),
                ('type', models.CharField(choices=[('A', 'Atoll'), ('I', 'Island'), ('C', 'Continental')], max_length=16)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='habitat.Location')),
            ],
        ),
        migrations.CreateModel(
            name='Substrate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=24, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='reefhabitat',
            name='habitat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='habitat.ReefType'),
        ),
        migrations.AddField(
            model_name='reefhabitat',
            name='reef',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='habitat.Reef'),
        ),
        migrations.AddField(
            model_name='reef',
            name='shark_gear_in_use',
            field=models.ManyToManyField(blank=True, to='habitat.SharkGearInUse'),
        ),
        migrations.AddField(
            model_name='reef',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='habitat.Site'),
        ),
        migrations.AddField(
            model_name='mpa',
            name='mpa_compliance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='habitat.MPACompliance'),
        ),
        migrations.AddField(
            model_name='mpa',
            name='mpa_isolation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='habitat.MPAIsolation'),
        ),
        migrations.AddField(
            model_name='location',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='habitat.Region'),
        ),
        migrations.AlterUniqueTogether(
            name='site',
            unique_together=set([('location', 'code'), ('location', 'name')]),
        ),
        migrations.AlterUniqueTogether(
            name='reef',
            unique_together=set([('site', 'code'), ('site', 'name')]),
        ),
    ]
