# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-11 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='code',
            field=models.CharField(default='x', help_text='ISO 3166 two-letter country code', max_length=2, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reef',
            name='code',
            field=models.CharField(default='x', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reeftype',
            name='code',
            field=models.CharField(default='x', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='site',
            name='code',
            field=models.CharField(default='x', max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='type',
            field=models.CharField(choices=[('A', 'Atoll'), ('I', 'Island'), ('C', 'Continental')], max_length=16),
        ),
        migrations.AlterUniqueTogether(
            name='reef',
            unique_together=set([('site', 'code'), ('site', 'name')]),
        ),
        migrations.AlterUniqueTogether(
            name='site',
            unique_together=set([('location', 'name'), ('location', 'code')]),
        ),
    ]
