# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-01 03:29
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reef',
            name='boundary',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='reef',
            name='code',
            field=models.CharField(help_text='Must be unique for reef site.', max_length=2),
        ),
        migrations.AlterField(
            model_name='site',
            name='boundary',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='site',
            name='type',
            field=models.CharField(choices=[('I', 'Island'), ('A', 'Atoll'), ('C', 'Continental')], max_length=1),
        ),
    ]
