# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-15 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitat', '0002_auto_20160201_0329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='code',
            field=models.CharField(help_text='3166-1 alpha-2, if applicable.', max_length=4, unique=True),
        ),
        migrations.AlterField(
            model_name='reef',
            name='code',
            field=models.CharField(help_text='Must be unique for reef site.', max_length=4),
        ),
        migrations.AlterField(
            model_name='site',
            name='code',
            field=models.CharField(help_text='Must be unique for site location.', max_length=4),
        ),
        migrations.AlterField(
            model_name='site',
            name='type',
            field=models.CharField(choices=[('I', 'Island'), ('C', 'Continental'), ('A', 'Atoll')], max_length=1),
        ),
    ]
