# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-11 21:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitat', '0003_auto_20160111_1316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reef',
            name='type',
        ),
        migrations.AlterField(
            model_name='site',
            name='type',
            field=models.CharField(choices=[('C', 'Continental'), ('A', 'Atoll'), ('I', 'Island')], max_length=16),
        ),
    ]
