# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-19 20:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20160412_2234'),
        ('habitat', '0003_auto_20160315_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='planned_team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Team'),
        ),
        migrations.AlterField(
            model_name='site',
            name='type',
            field=models.CharField(choices=[('C', 'Continental'), ('A', 'Atoll'), ('I', 'Island')], max_length=1),
        ),
    ]
