# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-01 15:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitat', '0004_auto_20160419_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reef',
            name='code',
            field=models.CharField(help_text='Must be unique for reef site.', max_length=5),
        ),
    ]
