# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-30 16:08
from __future__ import unicode_literals

from decimal import Decimal
import django.contrib.gis.db.models.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitat', '0005_auto_20160601_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mpa',
            name='area',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='km^2', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='mpa',
            name='boundary',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='mpa',
            name='founded',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='type',
            field=models.CharField(choices=[('I', 'Island'), ('C', 'Continental'), ('A', 'Atoll')], max_length=1),
        ),
    ]
