# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-05 03:42
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitat', '0006_auto_20160630_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='boundary',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='location',
            name='eez_boundary',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='site',
            name='type',
            field=models.CharField(choices=[('C', 'Continental'), ('I', 'Island'), ('A', 'Atoll')], max_length=1),
        ),
    ]
