# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-11-16 00:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('habitat', '0007_auto_20160705_0342'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubstrateComplexity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='reeftype',
            options={'verbose_name': 'Reef habitat'},
        ),
        migrations.AlterModelManagers(
            name='reef',
            managers=[
                ('old_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
