# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-06-06 21:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitat', '0008_auto_20161116_0027'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='substratecomplexity',
            options={'verbose_name_plural': 'substrate complexities'},
        ),
        migrations.AlterField(
            model_name='site',
            name='type',
            field=models.CharField(choices=[('A', 'Atoll'), ('C', 'Continental'), ('I', 'Island')], max_length=1),
        ),
    ]
