# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-06-16 09:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitat', '0010_auto_20170616_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='type',
            field=models.CharField(choices=[('C', 'Continental'), ('I', 'Island'), ('A', 'Atoll')], max_length=1),
        ),
    ]
