# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-15 20:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitat', '0012_auto_20170616_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='reef',
            name='name',
            field=models.CharField(db_index=True, help_text='Must be unique for reef site.', max_length=100),
        ),
        migrations.AlterField(
            model_name='site',
            name='name',
            field=models.CharField(db_index=True, help_text='Must be unique for site location.', max_length=100),
        ),
    ]
