# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-09-20 14:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitat', '0014_auto_20180225_0031'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SharkGearInUse',
            new_name='FishingGear',
        ),
        migrations.AlterModelOptions(
            name='fishinggear',
            options={'verbose_name_plural': 'Fishing Gear'},
        ),
        migrations.RenameField(
            model_name='reef',
            old_name='shark_gear_in_use',
            new_name='fishing_gear',
        ),
        migrations.AlterField(
            model_name='site',
            name='type',
            field=models.CharField(choices=[('C', 'Continental'), ('I', 'Island'), ('O', 'Offshore Bank'), ('B', 'Barrier Reef'), ('V', 'Volcanic Island'), ('A', 'Atoll')], max_length=1),
        ),
    ]
