# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-09-20 17:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitat', '0015_test1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='type',
            field=models.CharField(choices=[('I', 'Island'), ('V', 'Volcanic Island'), ('B', 'Barrier Reef'), ('O', 'Offshore Bank'), ('C', 'Continental'), ('A', 'Atoll')], max_length=1),
        ),
    ]
