# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-09-20 19:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitat', '0017_dummy_column'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='type',
            field=models.CharField(choices=[('V', 'Volcanic Island'), ('C', 'Continental'), ('I', 'Island'), ('A', 'Atoll'), ('O', 'Offshore Bank'), ('B', 'Barrier Reef')], max_length=1),
        ),
    ]
