# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-09-20 19:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitat', '0018_dummy_column'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='type',
            field=models.CharField(choices=[('B', 'Barrier Reef'), ('I', 'Island'), ('O', 'Offshore Bank'), ('V', 'Volcanic Island'), ('A', 'Atoll'), ('C', 'Continental')], max_length=1),
        ),
    ]
