# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-12 22:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20160412_2234'),
        ('trip', '0003_auto_20160302_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Team'),
        ),
        migrations.AlterUniqueTogether(
            name='team',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='team',
            name='lead',
        ),
        migrations.RemoveField(
            model_name='team',
            name='user',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
