# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-08 18:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0003_auto_20160302_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='POC', to='core.FinprintUser'),
        ),
    ]
