# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-08 18:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0004_auto_20160408_1804'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='team',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
