# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-08 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_team'),
        ('trip', '0005_remove_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='team',
            field=models.ForeignKey(to='core.Team'),
        ),
    ]
