# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-02 19:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0006_migrate_negative_embargo_to_pos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='code',
            field=models.CharField(max_length=3, unique=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='data_embargo_length',
            field=models.PositiveIntegerField(help_text='days to embargo data after trip ends', null=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='name',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='boat',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='code',
            field=models.CharField(blank=True, help_text='[source code]_[year]_[loc code]_xx', max_length=32, null=True, unique=True),
        ),
    ]
