# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-13 15:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0006_migrate_negative_embargo_to_pos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='code',
            field=models.CharField(max_length=3, unique=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='data_embargo_length',
            field=models.PositiveIntegerField(default=9999, help_text='Days to embargo data after trip ends. 9999 = "embargo forever"', null=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='name',
            field=models.CharField(default='Global Finprint', max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trip',
            name='boat',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='code',
            field=models.CharField(blank=True, help_text='[source code]_[year]_[loc code]_xx', max_length=32, null=True, unique=True),
        ),
    ]
