# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-01 01:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0007_auto_20160613_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='legacy',
            field=models.BooleanField(default=False),
        ),
    ]
