# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-01 03:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bruv', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bait',
            name='type',
            field=models.CharField(choices=[('CRS', 'Crushed'), ('CHP', 'Chopped'), ('WHL', 'Whole')], max_length=3),
        ),
        migrations.AlterField(
            model_name='environmentmeasure',
            name='current_direction',
            field=models.CharField(blank=True, choices=[('NE', 'Northeast'), ('W', 'West'), ('SW', 'Southwest'), ('SE', 'Southeast'), ('E', 'East'), ('NW', 'Northwest'), ('S', 'South'), ('N', 'North')], help_text='compass direction', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='environmentmeasure',
            name='surface_chop',
            field=models.CharField(blank=True, choices=[('M', 'Medium'), ('L', 'Light'), ('H', 'Heavy')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='environmentmeasure',
            name='tide_state',
            field=models.CharField(blank=True, choices=[('S', 'Slack'), ('S2F', 'Slack to Flood'), ('F', 'Flood'), ('E', 'Ebb'), ('S2E', 'Slack to Ebb')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='environmentmeasure',
            name='wind_direction',
            field=models.CharField(blank=True, choices=[('NE', 'Northeast'), ('W', 'West'), ('SW', 'Southwest'), ('SE', 'Southeast'), ('E', 'East'), ('NW', 'Northwest'), ('S', 'South'), ('N', 'North')], help_text='compass direction', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='bait_container',
            field=models.CharField(choices=[('B', 'Bag'), ('C', 'Cage')], default='C', max_length=1),
        ),
        migrations.AlterField(
            model_name='set',
            name='code',
            field=models.CharField(blank=True, help_text='[site + reef code]_xxx', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='set',
            name='reef_habitat',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='habitat.ReefHabitat'),
        ),
        migrations.AlterField(
            model_name='set',
            name='visibility',
            field=models.CharField(choices=[('15', '15'), ('13', '13'), ('>15', '>15'), ('6', '6'), ('5', '5'), ('4', '4'), ('2', '2'), ('14', '14'), ('10', '10'), ('1', '1'), ('11', '11'), ('9', '9'), ('7', '7'), ('12', '12'), ('8', '8'), ('3', '3')], max_length=3),
        ),
    ]
