# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-11 16:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bruv', '0002_add_video_to_set'),
    ]

    operations = [
        migrations.RenameField(
            model_name='set',
            old_name='drop_id',
            new_name='code',
        ),
    ]
