# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-02 00:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bruv', '0002_auto_20160201_0329'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='set',
            unique_together=set([('trip', 'code')]),
        ),
    ]
