# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-17 15:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bruv', '0003_auto_20160302_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bait',
            name='type',
            field=models.CharField(choices=[('CHP', 'Chopped'), ('CRS', 'Crushed'), ('WHL', 'Whole')], max_length=3),
        ),
        migrations.AlterField(
            model_name='environmentmeasure',
            name='current_direction',
            field=models.CharField(blank=True, choices=[('S', 'South'), ('W', 'West'), ('NE', 'Northeast'), ('SW', 'Southwest'), ('SE', 'Southeast'), ('NW', 'Northwest'), ('N', 'North'), ('E', 'East')], help_text='compass direction', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='environmentmeasure',
            name='estimated_wind_speed',
            field=models.IntegerField(blank=True, help_text='Beaufort', null=True),
        ),
        migrations.AlterField(
            model_name='environmentmeasure',
            name='surface_chop',
            field=models.CharField(blank=True, choices=[('H', 'Heavy'), ('M', 'Medium'), ('L', 'Light')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='environmentmeasure',
            name='tide_state',
            field=models.CharField(blank=True, choices=[('S', 'Slack'), ('E', 'Ebb'), ('S2F', 'Slack to Flood'), ('F', 'Flood'), ('S2E', 'Slack to Ebb')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='environmentmeasure',
            name='wind_direction',
            field=models.CharField(blank=True, choices=[('S', 'South'), ('W', 'West'), ('NE', 'Northeast'), ('SW', 'Southwest'), ('SE', 'Southeast'), ('NW', 'Northwest'), ('N', 'North'), ('E', 'East')], help_text='compass direction', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='frametype',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='set',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='set',
            name='visibility',
            field=models.CharField(choices=[('5', '5'), ('10', '10'), ('8', '8'), ('>15', '>15'), ('4', '4'), ('3', '3'), ('1', '1'), ('15', '15'), ('11', '11'), ('14', '14'), ('6', '6'), ('13', '13'), ('7', '7'), ('12', '12'), ('2', '2'), ('9', '9')], max_length=3),
        ),
    ]
