# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-15 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bruv', '0003_auto_20160111_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bait',
            name='type',
            field=models.CharField(choices=[('CHP', 'Chopped'), ('WHL', 'Whole'), ('CRS', 'Crushed')], max_length=3),
        ),
        migrations.AlterField(
            model_name='environmentmeasure',
            name='current_direction',
            field=models.CharField(blank=True, choices=[('N', 'North'), ('W', 'West'), ('S', 'South'), ('E', 'East'), ('NE', 'Northeast'), ('SE', 'Southeast'), ('SW', 'Southwest'), ('NW', 'Northwest')], help_text='compass direction', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='environmentmeasure',
            name='surface_chop',
            field=models.CharField(blank=True, choices=[('M', 'Medium'), ('H', 'Heavy'), ('L', 'Light')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='environmentmeasure',
            name='tide_state',
            field=models.CharField(blank=True, choices=[('S', 'Slack'), ('S2F', 'Slack to Flood'), ('E', 'Ebb'), ('F', 'Flood'), ('S2E', 'Slack to Ebb')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='environmentmeasure',
            name='wind_direction',
            field=models.CharField(blank=True, choices=[('N', 'North'), ('W', 'West'), ('S', 'South'), ('E', 'East'), ('NE', 'Northeast'), ('SE', 'Southeast'), ('SW', 'Southwest'), ('NW', 'Northwest')], help_text='compass direction', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='set',
            name='code',
            field=models.CharField(help_text='[site + reef code]_xxx', max_length=32),
        ),
        migrations.AlterField(
            model_name='set',
            name='visibility',
            field=models.CharField(choices=[('11', '11'), ('12', '12'), ('>15', '>15'), ('9', '9'), ('8', '8'), ('2', '2'), ('4', '4'), ('14', '14'), ('7', '7'), ('5', '5'), ('6', '6'), ('10', '10'), ('3', '3'), ('15', '15'), ('1', '1'), ('13', '13')], max_length=3),
        ),
    ]
