# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-18 14:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bruv', '0003_auto_20160302_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bait',
            name='type',
            field=models.CharField(choices=[('WHL', 'Whole'), ('CRS', 'Crushed'), ('CHP', 'Chopped')], max_length=3),
        ),
        migrations.AlterField(
            model_name='environmentmeasure',
            name='current_direction',
            field=models.CharField(blank=True, choices=[('NW', 'Northwest'), ('S', 'South'), ('SE', 'Southeast'), ('SW', 'Southwest'), ('E', 'East'), ('W', 'West'), ('N', 'North'), ('NE', 'Northeast')], help_text='compass direction', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='environmentmeasure',
            name='estimated_wind_speed',
            field=models.IntegerField(blank=True, help_text='Beaufort', null=True),
        ),
        migrations.AlterField(
            model_name='environmentmeasure',
            name='surface_chop',
            field=models.CharField(blank=True, choices=[('M', 'Medium'), ('H', 'Heavy'), ('L', 'Light')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='environmentmeasure',
            name='tide_state',
            field=models.CharField(blank=True, choices=[('S', 'Slack'), ('S2E', 'Slack to Ebb'), ('E', 'Ebb'), ('F', 'Flood'), ('S2F', 'Slack to Flood')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='environmentmeasure',
            name='wind_direction',
            field=models.CharField(blank=True, choices=[('NW', 'Northwest'), ('S', 'South'), ('SE', 'Southeast'), ('SW', 'Southwest'), ('E', 'East'), ('W', 'West'), ('N', 'North'), ('NE', 'Northeast')], help_text='compass direction', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='frametype',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='set',
            name='bait',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bruv.Bait'),
        ),
        migrations.AlterField(
            model_name='set',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='set',
            name='visibility',
            field=models.CharField(choices=[('9', '9'), ('>15', '>15'), ('7', '7'), ('12', '12'), ('6', '6'), ('1', '1'), ('8', '8'), ('4', '4'), ('11', '11'), ('5', '5'), ('3', '3'), ('15', '15'), ('14', '14'), ('10', '10'), ('2', '2'), ('13', '13')], max_length=3),
        ),
    ]
