# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-01 02:55
from __future__ import unicode_literals

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bruv', '0004_auto_20160518_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='set',
            name='depth',
            field=models.DecimalField(decimal_places=2, help_text='m', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
