# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-15 14:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bruv', '0005_auto_20160701_0255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bait',
            name='type',
            field=models.CharField(choices=[('CHP', 'Chopped'), ('WHL', 'Whole'), ('CRS', 'Crushed')], max_length=3),
        ),
        migrations.AlterField(
            model_name='environmentmeasure',
            name='current_direction',
            field=models.CharField(blank=True, choices=[('E', 'East'), ('N', 'North'), ('SW', 'Southwest'), ('W', 'West'), ('NW', 'Northwest'), ('S', 'South'), ('NE', 'Northeast'), ('SE', 'Southeast')], help_text='compass direction', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='environmentmeasure',
            name='tide_state',
            field=models.CharField(blank=True, choices=[('S2F', 'Slack to Flood'), ('S2E', 'Slack to Ebb'), ('F', 'Flood'), ('S', 'Slack'), ('E', 'Ebb')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='environmentmeasure',
            name='wind_direction',
            field=models.CharField(blank=True, choices=[('E', 'East'), ('N', 'North'), ('SW', 'Southwest'), ('W', 'West'), ('NW', 'Northwest'), ('S', 'South'), ('NE', 'Northeast'), ('SE', 'Southeast')], help_text='compass direction', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='bait_container',
            field=models.CharField(choices=[('C', 'Cage'), ('B', 'Bag')], default='C', max_length=1),
        ),
        migrations.AlterField(
            model_name='set',
            name='latitude',
            field=models.DecimalField(decimal_places=8, max_digits=12),
        ),
        migrations.AlterField(
            model_name='set',
            name='longitude',
            field=models.DecimalField(decimal_places=8, max_digits=12),
        ),
        migrations.AlterField(
            model_name='set',
            name='visibility',
            field=models.CharField(choices=[('1', '1'), ('>15', '>15'), ('7', '7'), ('11', '11'), ('10', '10'), ('5', '5'), ('4', '4'), ('13', '13'), ('9', '9'), ('3', '3'), ('2', '2'), ('14', '14'), ('8', '8'), ('0', 'LEGACY'), ('12', '12'), ('6', '6'), ('15', '15')], max_length=3),
        ),
    ]
