# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-19 16:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bruv', '0005_auto_20160701_0255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bait',
            name='description',
            field=models.CharField(help_text='1kg', max_length=32),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='camera',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='frametype',
            name='type',
            field=models.CharField(max_length=32),
        ),
    ]
