# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-20 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bruv', '0007_auto_20160719_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='environmentmeasure',
            name='conductivity',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='S/m', max_digits=8, null=True),
        ),
    ]
