# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-19 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bruv', '0007_migrate_dupe_bait'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bait',
            name='type',
            field=models.CharField(choices=[('CRS', 'Crushed'), ('CHP', 'Chopped'), ('WHL', 'Whole')], max_length=3),
        ),
        migrations.AlterField(
            model_name='environmentmeasure',
            name='current_direction',
            field=models.CharField(blank=True, choices=[('SE', 'Southeast'), ('N', 'North'), ('SW', 'Southwest'), ('E', 'East'), ('NW', 'Northwest'), ('NE', 'Northeast'), ('S', 'South'), ('W', 'West')], help_text='compass direction', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='environmentmeasure',
            name='surface_chop',
            field=models.CharField(blank=True, choices=[('H', 'Heavy'), ('L', 'Light'), ('M', 'Medium')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='environmentmeasure',
            name='tide_state',
            field=models.CharField(blank=True, choices=[('S2F', 'Slack to Flood'), ('S', 'Slack'), ('S2E', 'Slack to Ebb'), ('F', 'Flood'), ('E', 'Ebb')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='environmentmeasure',
            name='wind_direction',
            field=models.CharField(blank=True, choices=[('SE', 'Southeast'), ('N', 'North'), ('SW', 'Southwest'), ('E', 'East'), ('NW', 'Northwest'), ('NE', 'Northeast'), ('S', 'South'), ('W', 'West')], help_text='compass direction', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='set',
            name='visibility',
            field=models.CharField(choices=[('11', '11'), ('5', '5'), ('13', '13'), ('9', '9'), ('14', '14'), ('8', '8'), ('4', '4'), ('3', '3'), ('10', '10'), ('6', '6'), ('7', '7'), ('2', '2'), ('1', '1'), ('0', 'LEGACY'), ('>15', '>15'), ('15', '15'), ('12', '12')], max_length=3),
        ),
        migrations.AlterUniqueTogether(
            name='bait',
            unique_together=set([('description', 'type', 'oiled')]),
        ),
    ]
