# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-27 17:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bruv', '0008_auto_20160720_1805'),
        ('bruv', '0009_fix_misspelling'),
    ]

    operations = [
    ]
