# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-11 20:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bruv', '0011_auto_20160811_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='set',
            name='bruv_image_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='set',
            name='current_flow_estimated',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='set',
            name='current_flow_instrumented',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='m/s', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='set',
            name='splendor_image_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
