# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-16 18:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bruv', '0012_auto_20160811_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='environmentmeasure',
            name='measured_wind_speed',
            field=models.IntegerField(blank=True, help_text='kts', null=True),
        ),
    ]
