# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-19 20:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bruv', '0013_auto_20160816_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='environmentmeasure',
            name='dissolved_oxygen',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=8, null=True),
        ),
    ]
