# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-02 16:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bruv', '0015_auto_20160822_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='set',
            name='haul_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
