# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-20 16:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bruv', '0016_auto_20160902_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='set',
            name='haul_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
