# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-10-25 23:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bruv', '0018_update_haul_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='set',
            name='current_flow_estimated',
            field=models.CharField(blank=True, help_text='H, M, L', max_length=50, null=True),
        ),
    ]
