# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-11-15 19:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bruv', '0019_auto_20161025_2316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='set',
            name='substrate',
        ),
        migrations.RenameModel(
            old_name='Substrate',
            new_name='BenthicCategory',
        ),
        migrations.RenameModel(
            old_name='HabitatSubstrate',
            new_name='BenthicCategoryValue',
        ),
        migrations.AddField(
            model_name='set',
            name='benthic_category',
            field=models.ManyToManyField(through='bruv.BenthicCategoryValue', to='bruv.BenthicCategory'),
        ),

    ]
