# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-11-15 20:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bruv', '0020_auto_20161115_1923'),
    ]

    operations = [
        migrations.RenameField(
            model_name='benthiccategoryvalue',
            old_name='substrate',
            new_name='benthic_category',
        ),
    ]
