# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-02-27 23:28
from __future__ import unicode_literals

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bruv', '0022_auto_20161116_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='set',
            name='depth',
            field=models.DecimalField(decimal_places=2, default=0, help_text='m', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
            preserve_default=False,
        ),
    ]
