# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-06-06 21:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bruv', '0023_auto_20170227_2328'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='benthiccategory',
            options={'verbose_name_plural': 'benthic categories'},
        ),
    ]
