# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-06-16 09:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('bruv', '0025_auto_20170607_1420'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='benthiccategory',
            managers=[
                ('objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='settag',
            managers=[
                ('objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='bait',
            name='type',
            field=models.CharField(choices=[('CHP', 'Chopped'), ('CRS', 'Crushed'), ('WHL', 'Whole')], max_length=3),
        ),
        migrations.AlterField(
            model_name='environmentmeasure',
            name='current_direction',
            field=models.CharField(blank=True, choices=[('E', 'East'), ('SW', 'Southwest'), ('W', 'West'), ('SE', 'Southeast'), ('NW', 'Northwest'), ('NE', 'Northeast'), ('N', 'North'), ('S', 'South')], help_text='compass direction', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='environmentmeasure',
            name='surface_chop',
            field=models.CharField(blank=True, choices=[('M', 'Medium'), ('L', 'Light'), ('H', 'Heavy')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='environmentmeasure',
            name='tide_state',
            field=models.CharField(blank=True, choices=[('E', 'Ebb'), ('S2F', 'Slack to Flood'), ('S2E', 'Slack to Ebb'), ('F', 'Flood'), ('S', 'Slack')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='environmentmeasure',
            name='wind_direction',
            field=models.CharField(blank=True, choices=[('E', 'East'), ('SW', 'Southwest'), ('W', 'West'), ('SE', 'Southeast'), ('NW', 'Northwest'), ('NE', 'Northeast'), ('N', 'North'), ('S', 'South')], help_text='compass direction', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='bait_container',
            field=models.CharField(choices=[('B', 'Bag'), ('C', 'Cage')], default='C', max_length=1),
        ),
        migrations.AlterField(
            model_name='set',
            name='visibility',
            field=models.CharField(choices=[('7', '7'), ('0', 'LEGACY'), ('9', '9'), ('2', '2'), ('15', '15'), ('5', '5'), ('12', '12'), ('3', '3'), ('6', '6'), ('4', '4'), ('8', '8'), ('13', '13'), ('10', '10'), ('14', '14'), ('>15', '>15'), ('11', '11'), ('1', '1')], help_text='m', max_length=3),
        ),
    ]
