# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-06-16 09:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bruv', '0026_auto_20170616_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bait',
            name='type',
            field=models.CharField(choices=[('CRS', 'Crushed'), ('WHL', 'Whole'), ('CHP', 'Chopped')], max_length=3),
        ),
        migrations.AlterField(
            model_name='environmentmeasure',
            name='current_direction',
            field=models.CharField(blank=True, choices=[('SW', 'Southwest'), ('SE', 'Southeast'), ('NW', 'Northwest'), ('S', 'South'), ('N', 'North'), ('W', 'West'), ('E', 'East'), ('NE', 'Northeast')], help_text='compass direction', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='environmentmeasure',
            name='surface_chop',
            field=models.CharField(blank=True, choices=[('H', 'Heavy'), ('L', 'Light'), ('M', 'Medium')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='environmentmeasure',
            name='tide_state',
            field=models.CharField(blank=True, choices=[('E', 'Ebb'), ('S2F', 'Slack to Flood'), ('S2E', 'Slack to Ebb'), ('S', 'Slack'), ('F', 'Flood')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='environmentmeasure',
            name='wind_direction',
            field=models.CharField(blank=True, choices=[('SW', 'Southwest'), ('SE', 'Southeast'), ('NW', 'Northwest'), ('S', 'South'), ('N', 'North'), ('W', 'West'), ('E', 'East'), ('NE', 'Northeast')], help_text='compass direction', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='bait_container',
            field=models.CharField(choices=[('C', 'Cage'), ('B', 'Bag')], default='C', max_length=1),
        ),
        migrations.AlterField(
            model_name='set',
            name='visibility',
            field=models.CharField(choices=[('0', 'LEGACY'), ('12', '12'), ('14', '14'), ('>15', '>15'), ('15', '15'), ('7', '7'), ('4', '4'), ('11', '11'), ('13', '13'), ('5', '5'), ('3', '3'), ('1', '1'), ('10', '10'), ('9', '9'), ('6', '6'), ('2', '2'), ('8', '8')], help_text='m', max_length=3),
        ),
    ]
