# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-13 19:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bruv', '0028_auto_20170616_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='set',
            name='bulk_loaded',
            field=models.BooleanField(default=False),
        ),

        migrations.RunSQL('''
            BEGIN TRANSACTION;
            
            UPDATE bruv_set
            SET bulk_loaded = TRUE
            WHERE comments LIKE '%BULK UPLOAD';
            
            UPDATE bruv_set
            SET comments =
            substring(comments FROM 0 FOR char_length(comments) - char_length(' -- BULK UPLOAD') + 1)
            WHERE comments LIKE '% -- BULK UPLOAD';
            
            UPDATE bruv_set
            SET comments =
            substring(comments FROM 0 FOR char_length(comments) - char_length('BULK UPLOAD') + 1)
            WHERE comments LIKE '%BULK UPLOAD';
            
            COMMIT TRANSACTION;
        '''),
    ]
