# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-15 20:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bruv', '0029_auto_20170813_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='set',
            name='code',
            field=models.CharField(blank=True, db_index=True, help_text='[site + reef code]_xxx', max_length=32, null=True),
        ),
    ]
