# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-30 22:22
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bruv', '0030_auto_20170815_2045'),
    ]

    operations = [
        migrations.RunSQL('''
                BEGIN TRANSACTION;
                
                UPDATE bruv_set
                SET visibility =
                (
                  CASE
                  WHEN visibility IN ('L', 'M', 'H', '0', '')
                    THEN '-1'
                  WHEN visibility IS NULL
                    THEN '-1'
                  WHEN visibility = '>15'
                    THEN '20'
                  ELSE
                    visibility
                  END
                );
                
                COMMIT TRANSACTION;
            '''),

        migrations.AlterField(
            model_name='set',
            name='visibility',
            field=models.IntegerField(blank=True, help_text='m', null=True, validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(50)]),
        ),
    ]
