# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-09 21:18
from __future__ import unicode_literals

import config.current_user
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bruv', '0032_auto_20170906_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='bait',
            name='last_modified_by',
            field=models.ForeignKey(default=config.current_user.get_current_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bruv_bait_last_modified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='environmentmeasure',
            name='last_modified_by',
            field=models.ForeignKey(default=config.current_user.get_current_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bruv_environmentmeasure_last_modified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='equipment',
            name='last_modified_by',
            field=models.ForeignKey(default=config.current_user.get_current_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bruv_equipment_last_modified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='set',
            name='last_modified_by',
            field=models.ForeignKey(default=config.current_user.get_current_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bruv_set_last_modified_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
