# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-09-20 14:32
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bruv', '0034_auto_20171113_1849'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipment',
            options={'ordering': ['frame_type__type', 'container__type', 'camera'], 'verbose_name_plural': 'Equipment'},
        ),
        migrations.RemoveField(
            model_name='set',
            name='substrate',
        ),
        migrations.RemoveField(
            model_name='set',
            name='substrate_complexity',
        ),
        migrations.AddField(
            model_name='set',
            name='custom_field_value',
            field=django.contrib.postgres.fields.jsonb.JSONField(db_column='custom_fields', null=True),
        ),
        migrations.AddField(
            model_name='set',
            name='field_of_view',
            field=models.CharField(blank=True, choices=[('FD', 'Facing Down'), ('FU', 'Facing Up'), ('O', 'Open'), ('L', 'Limited')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='set',
            name='substrate_relief_mean',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='set',
            name='substrate_relief_sd',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='environmentmeasure',
            name='current_direction',
            field=models.CharField(blank=True, choices=[('NW', 'Northwest'), ('E', 'East'), ('W', 'West'), ('N', 'North'), ('SE', 'Southeast'), ('SW', 'Southwest'), ('S', 'South'), ('NE', 'Northeast')], help_text='compass direction', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='environmentmeasure',
            name='tide_state',
            field=models.CharField(blank=True, choices=[('E', 'Ebb'), ('S2E', 'Slack to Ebb'), ('F', 'Flood'), ('S2F', 'Slack to Flood'), ('S', 'Slack')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='environmentmeasure',
            name='wind_direction',
            field=models.CharField(blank=True, choices=[('NW', 'Northwest'), ('E', 'East'), ('W', 'West'), ('N', 'North'), ('SE', 'Southeast'), ('SW', 'Southwest'), ('S', 'South'), ('NE', 'Northeast')], help_text='compass direction', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='set',
            name='visibility',
            field=models.CharField(blank=True, choices=[('V2-4', 'V2-4'), ('V8-10', 'V8-10'), ('V4-6', 'V4-6'), ('V6-8', 'V6-8'), ('V10+', 'V10+'), ('V0-2', 'V0-2')], db_column='visibility_str', max_length=10, null=True),
        ),
    ]
