# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-09-20 17:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bruv', '0035_test1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bait',
            name='type',
            field=models.CharField(choices=[('CRS', 'Crushed'), ('CHP', 'Chopped'), ('WHL', 'Whole')], max_length=3),
        ),
        migrations.AlterField(
            model_name='environmentmeasure',
            name='current_direction',
            field=models.CharField(blank=True, choices=[('SW', 'Southwest'), ('SE', 'Southeast'), ('NW', 'Northwest'), ('N', 'North'), ('S', 'South'), ('NE', 'Northeast'), ('E', 'East'), ('W', 'West')], help_text='compass direction', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='environmentmeasure',
            name='surface_chop',
            field=models.CharField(blank=True, choices=[('H', 'Heavy'), ('M', 'Medium'), ('L', 'Light')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='environmentmeasure',
            name='tide_state',
            field=models.CharField(blank=True, choices=[('E', 'Ebb'), ('S2F', 'Slack to Flood'), ('F', 'Flood'), ('S2E', 'Slack to Ebb'), ('S', 'Slack')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='environmentmeasure',
            name='wind_direction',
            field=models.CharField(blank=True, choices=[('SW', 'Southwest'), ('SE', 'Southeast'), ('NW', 'Northwest'), ('N', 'North'), ('S', 'South'), ('NE', 'Northeast'), ('E', 'East'), ('W', 'West')], help_text='compass direction', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='set',
            name='field_of_view',
            field=models.CharField(blank=True, choices=[('FU', 'Facing Up'), ('L', 'Limited'), ('FD', 'Facing Down'), ('O', 'Open')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='set',
            name='visibility',
            field=models.CharField(blank=True, choices=[('V8-10', 'V8-10'), ('V4-6', 'V4-6'), ('V6-8', 'V6-8'), ('V10+', 'V10+'), ('V2-4', 'V2-4'), ('V0-2', 'V0-2')], db_column='visibility_str', max_length=10, null=True),
        ),
    ]
