# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-09-20 19:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bruv', '0036_new_features'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bait',
            name='type',
            field=models.CharField(choices=[('CRS', 'Crushed'), ('WHL', 'Whole'), ('CHP', 'Chopped')], max_length=3),
        ),
        migrations.AlterField(
            model_name='environmentmeasure',
            name='current_direction',
            field=models.CharField(blank=True, choices=[('W', 'West'), ('SE', 'Southeast'), ('NW', 'Northwest'), ('E', 'East'), ('S', 'South'), ('N', 'North'), ('SW', 'Southwest'), ('NE', 'Northeast')], help_text='compass direction', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='environmentmeasure',
            name='surface_chop',
            field=models.CharField(blank=True, choices=[('L', 'Light'), ('H', 'Heavy'), ('M', 'Medium')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='environmentmeasure',
            name='tide_state',
            field=models.CharField(blank=True, choices=[('S', 'Slack'), ('S2F', 'Slack to Flood'), ('F', 'Flood'), ('S2E', 'Slack to Ebb'), ('E', 'Ebb')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='environmentmeasure',
            name='wind_direction',
            field=models.CharField(blank=True, choices=[('W', 'West'), ('SE', 'Southeast'), ('NW', 'Northwest'), ('E', 'East'), ('S', 'South'), ('N', 'North'), ('SW', 'Southwest'), ('NE', 'Northeast')], help_text='compass direction', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='set',
            name='field_of_view',
            field=models.CharField(blank=True, choices=[('L', 'Limited'), ('FU', 'Facing Up'), ('FD', 'Facing Down'), ('O', 'Open')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='set',
            name='visibility',
            field=models.CharField(blank=True, choices=[('V4-6', 'V4-6'), ('V8-10', 'V8-10'), ('V2-4', 'V2-4'), ('V0-2', 'V0-2'), ('V6-8', 'V6-8'), ('V10+', 'V10+')], db_column='visibility_str', max_length=10, null=True),
        ),
    ]
