# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-09-20 20:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bruv', '0039_dummy_column'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bait',
            name='type',
            field=models.CharField(choices=[('WHL', 'Whole'), ('CHP', 'Chopped'), ('CRS', 'Crushed')], max_length=3),
        ),
        migrations.AlterField(
            model_name='environmentmeasure',
            name='current_direction',
            field=models.CharField(blank=True, choices=[('W', 'West'), ('S', 'South'), ('N', 'North'), ('SW', 'Southwest'), ('SE', 'Southeast'), ('E', 'East'), ('NW', 'Northwest'), ('NE', 'Northeast')], help_text='compass direction', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='environmentmeasure',
            name='surface_chop',
            field=models.CharField(blank=True, choices=[('M', 'Medium'), ('H', 'Heavy'), ('L', 'Light')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='environmentmeasure',
            name='tide_state',
            field=models.CharField(blank=True, choices=[('F', 'Flood'), ('S2F', 'Slack to Flood'), ('S', 'Slack'), ('S2E', 'Slack to Ebb'), ('E', 'Ebb')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='environmentmeasure',
            name='wind_direction',
            field=models.CharField(blank=True, choices=[('W', 'West'), ('S', 'South'), ('N', 'North'), ('SW', 'Southwest'), ('SE', 'Southeast'), ('E', 'East'), ('NW', 'Northwest'), ('NE', 'Northeast')], help_text='compass direction', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='set',
            name='field_of_view',
            field=models.CharField(blank=True, choices=[('FU', 'Facing Up'), ('FD', 'Facing Down'), ('O', 'Open'), ('L', 'Limited')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='set',
            name='visibility',
            field=models.CharField(blank=True, choices=[('V4-6', 'V4-6'), ('V10+', 'V10+'), ('V8-10', 'V8-10'), ('V6-8', 'V6-8'), ('V2-4', 'V2-4'), ('V0-2', 'V0-2')], db_column='visibility_str', max_length=10, null=True),
        ),
    ]
