# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-06-06 21:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20160412_2234'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='finprintuser',
            options={'ordering': ['user__last_name', 'user__first_name']},
        ),
    ]
