# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-12-14 21:59
from __future__ import unicode_literals

from django.db import migrations

def create_automation_group(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    g = Group(name='automation')
    g.save()

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20171113_1849'),
    ]

    operations = [
        migrations.RunPython(create_automation_group)
    ]
